# Generated by Django 2.0.4 on 2018-04-12 21:01

from django.db import migrations, models
import src.product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(default=src.product.models.get_default_product_id, help_text='ID generated for products as a reference if product fails', max_length=50, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=99)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
            },
        ),
    ]
